'use strict';

const ERROR_CODES = Object.freeze({
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  DUPLICATE_SKU: 'DUPLICATE_SKU',
  INVALID_JSON: 'INVALID_JSON',
  INVALID_URL: 'INVALID_URL',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  INVALID_QUERY_PARAM: 'INVALID_QUERY_PARAM',
  MEDIA_REQUIRED: 'MEDIA_REQUIRED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
});

module.exports = ERROR_CODES;
